#DATA
data_root: /opt/data/private/zjm/UTnetV2_new/dataset/flare21
classes: 5
modality: mri


#MODEL
arch: MSUmoe
init_model: '/opt/data/private/zjm/UTnetV2_new/pretrained/swin_tiny_patch4_window7_224.pth'

#TRAIN
#epochs: 1500
epochs: 150
training_size: [224, 224]    # training crop size
start_epoch: 0

seed: 1
k_fold: 1


optimizer: adamw
base_lr: 0.0001
#base_lr: 0.00006  #new
betas: [0.9, 0.999]
#weight_decay: 0.05  # weight decay of SGD optimizer
weight_decay: 0.0001  #new
weight: [0.5, 1, 1, 1,1]  # weitght of each class in the loss function
rlt: 1 # relation between CE and Dice loss

scale: 0.3  # scale for data augmentation
rotate: 180 # rotation angle for data augmentation
translate: 0
gaussian_noise_std: 0.02
additive_brightness_std: 0.7
gamma_range: [0.5, 1.6]


#VALIDATION
ema: False
ema_alpha: 0.99
val_frequency: 1

#INFERENCE
sliding_window: False
